config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'
  devise_for :users
  resources :homes, only: [:index, :show]
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image

  validates :text, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: { message: "can't be blank" } do
    validates :nickname,      uniqueness: { message: "has already been taken"}
  end

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_one_attached :image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: [:index, :create]

  def index
    @message = Message.new
    @messages = @room.messages.includes(:user)
  end

  def create
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_messages_path(@room)
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :image, :profile_text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<%= render "shared/header" %>

<div class='content'>
  <%= render "shared/side_bar" %>
  <div class='homes-index-div'>
    <% User.where.not(id: current_user.id).each do |user| %>
      <div class='users-div'>
        <div class='homes-member-icon'>
          <% if user.image.attached? %>
            <%= image_tag user.image.variant(resize: '200x200') %>
          <% else %>
            <i class="far fa-user user-icon-i fa-5x"></i>
          <% end %>
        </div>

        <div class='homes-name-text' >
          <div class='homes-name'><%= link_to user.nickname, user_path(user.id) %></div>
          <div class='homes-text'><%= user.profile_text %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/homes/show.html.erb
<%= render "shared/header" %>

<div>
  <%= @user.nickname %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamebo</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="/app/assets/stylesheets/lightbox.min.css">
    <script type="text/javascript" src="/app/javascript/lightbox.min.js"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<%= render "shared/header" %>

<div class='content'>
  <%= render "shared/side_bar" %>
  <div class='chat'>
    <%= render "shared/chat" %>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render "shared/header" %>

<div class='content'>
  <%= render "shared/side_bar" %>
  <div class='create-room-main'>
    <div class='create-room-page-div'>
      <div class='create-room-div'>
        <h2>チャットルーム作成</h2>
      </div>
      <%= form_with model: @room do |f| %>
      <div class='create-room-div'>
      
        <%= render 'shared/error_messages', model: f.object %>
        <div><%= f.label :チャットルーム名, class: 'create-room-label' %></div>
        <div><%= f.text_field :name, class: 'create-room-input-name' %></div>
      </div>

      <div class='create-room-div box-div'>
        <h3>メンバーを選択</h3>
        <% User.where.not(id: current_user.id).each do |user| %>
          <label class='check-label-div'>
            <input type='checkbox' class='check-box' name='room[user_ids][]' value=<%= user.id %>>
            <div class='check-member-icon'>
              <% if user.image.attached? %>
                <%= image_tag user.image.variant(resize: '60x60') %>
              <% else %>
                <i class="far fa-user user-icon-i fa-3x"></i>
              <% end %>
            </div>
            <div class='check-user-name'>
              <%= user.nickname %>
            </div>
          </label>
        <% end %>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
        <%# <button class='plus' id='plus'>+</button> %>
      </div>

      <div class='create-room-div'>
        <div><%= f.submit class: 'create-room-btn' %></div>
      
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_chat.html.erb
<div class='chat-header'>
  <div class='chat-header-title'>
    <%= @room.name %>
  </div>
  <div class='chat-menu-div'>
    <ul class='chat-list-ul'>
      <li class='drop-menu'>
        <i class="fas fa-list drop-menu-btn"></i>
        <ul class='drop-element'>
          <li><%= link_to "ルームを削除", room_path(@room), method: :delete %></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

<div class='messages', id='messages'>
  <%= link_to "publicdomainq-0022995sdv",'/assets/publicdomainq-0022995sdv.jpg',:rel => "lightbox"%>
  <%= render partial: 'shared/message', collection: @messages %>
</div>

<%= form_with model: [@room, @message], class: 'form' do |f| %>
  <div class='form-input'>
    <%= f.text_area :text, class: 'form-message', placeholder: 'メッセージを入力' %>
    <label class='form-image'>
      <i class="far fa-image"></i>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <div class='submit-div'>
    <label class='form-submit'>
      <i class="far fa-paper-plane"></i>
      <%= f.submit '送信', class: 'hidden' %>
    </label>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class='error-alert'>
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='logo-div'>
    <h1 class='logo'><%= link_to 'Gamebo', root_path %><i class="fas fa-headset logo-i"></i></h1>
  </div>
  <div>
    <ul class='header-list'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_login_header.html.erb
<div class='in-header'>
  <div class='logo-div'>
    <h1 class='logo'><%= link_to 'Gamebo', root_path %><i class="fas fa-headset logo-i"></i></h1>
  </div>
  <%= link_to '新規登録はこちら', new_user_registration_path, class: 'log-sign' %>
</div>

app/views/shared/_message.html.erb
<% if current_user.id == message.user.id %>
  <% if message.text.present? %>
    <div class="message message-right">
      <div class="lower-message">
        <div class="message-text right-text">
          <%= simple_format(message.text) %>
        </div>
        <div class="message-date">
          <%= message.created_at.strftime("%p %I:%M") %>
        </div>
      </div>
    </div>
  <% end %>
  <%= link_to image_tag message.image.variant(resize: '400x400'), message.user.image, class: 'message-image-right', :rel => "lightbox" if message.image.attached? %>
<% else %>
  <% if message.text.present? %>
    <div class="message message-left">
      <div class="upper-message">
        <div class='chat-icon'>
          <% if message.user.image.attached? %>
            <%= image_tag message.user.image.variant(resize: '100x100') %>
          <% else %>
            <i class="far fa-user user-icon-i"></i>
          <% end %>
        </div>
      </div>

      <div class="lower-message">
        <div class="message-user">
          <%= message.user.nickname %>
        </div>
        <div class="message-text left-text">
          <%= simple_format(message.text) %>
        </div>
        <div class="message-date">
          <%= message.created_at.strftime("%p %I:%M") %>
        </div>
      </div>
    </div>
  <% end %>
  <%= link_to image_tag message.image.variant(resize: '400x400'), class: 'message-image-left' if message.image.attached? %>
<% end %>

app/views/shared/_side_bar.html.erb
<div class='side'>
  <div class='rooms'>
    <p class='side-title'><i class="fas fa-caret-down side-title-mark"></i>チャットルーム</p>
    <% current_user.rooms.each do |room| %>
      <div class="room">
        <div class="room-name">
          <%= link_to room.name, room_messages_path(room) %>
        </div>
      </div>
    <% end %>
  </div>

  <div class='new-room-div'>
    <label class='new-room-label'>
      <%= link_to image_tag('fa-plus.png', class: 'new-room-image'), new_room_path %>
    </label>
  </div>
</div>

app/views/shared/_signup_header.html.erb
<div class='in-header'>
  <div class='logo-div'>
    <h1 class='logo'><%= link_to 'Gamebo', root_path %><i class="fas fa-headset logo-i"></i></h1>
  </div>
  <%= link_to 'ログインはこちら', new_user_session_path, class: 'log-sign' %>
</div>

app/views/users/edit.html.erb
<%= render "shared/header" %>

<div class='content'>
  <%= render "shared/side_bar" %>
  <div class='main'>
    <%= form_with model: @user do |f| %>
    <div class='edit-div'>
      <div class='edit-element'><%= f.text_field :nickname, class: 'edit-nickname f', placeholder: 'ニックネーム' %></div>
      <div class='edit-element'><%= f.file_field :image, class: 'edit-image f' %></div>
      <div class='edit-element'><%= f.text_area :profile_text, class: 'edit-profile f' %></div>
      <div class='edit-element'><%= f.submit '保存', class: 'edit-btn' %></div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class='content'>
  <%= render "shared/side_bar" %>
  <div class='main'>
    <% if current_user.id == @user.id %>
    <%= link_to 'ステータスを編集する', edit_user_path(current_user), class: 'user-edit-a' %>
    <% end %>
    <div class='upper-user-page-icon'>
      <% if @user.image.attached? %>
        <div class='div-user-page-icon'>
          <%= image_tag @user.image.variant(resize: '420x420') %>
        </div>
      <% else %>
        <div class='div-user-page-icon'>
          <i class="far fa-user normal-icon"></i>
        </div>
      <% end %>
    </div>

    <div class='user-name'><%= @user.nickname %></div>
    <div class='user-text'><%= @user.profile_text %></div>
  </div>
</div>